### ISSUE TITLE
Add schematics of the sensor

### ISSUE THREAD

**Issue by mrx23dot** [markniu/Bed_Distance_sensor#2]

**Comment by andreac** [comment]
+1

**Comment by markniu** [comment]
Thanks for feedback this! 
Actually, I would like to open source this, but I really want to find a way to support me to continue working in the 3D printing world. and the key of this sensor is the schematics :)

**Comment by markniu** [comment]
It use the normal inductive proximity sensor chip  https://www.infineon.com/dgdl/Infineon-TCA305-DS-v01_01-en%5B1%5D.pdf?fileId=db3a304412b407950112b437b522688a  after reading that I know how inductive senosr works and then how to make my idea come true.

**Comment by ptegler** [comment]
refing mrx23dot comment...this is the only way it will ever work with Klipper. (settable trigger switch point) The realtime data is perfect for fast bed mesh testing as designed, but needs as swutch point.

Might i suggest markniu, that you contact BigtreeTech and converse regarding firmware support directly to their Octopus and SKR line of boards, rather than expecting Klipper to directly control the sensor.
There was a pull for I2C issues for one of their boards....
https://github.com/Klipper3d/klipper/issues/5092

Also you might want to take a look at 
https://github.com/Klipper3d/klipper
to understand the I2C issues and their application in Klipper for the various boards

**Comment by markniu** [comment]
if we want to use it as settable trigger like proximity sensor, we need to add a new wires that connect to the sensor chip not data bus wires i2c to the mcu chip and also need a adjustable resistor like normal inductive proximity sensor, and there are so many that inductive sensor in the market.

The klipper has two parts software one is klippy written with python which runs on raspberrypi and another one is klipper written with C code which runs on MCU like stm32, so I think all the sensors are controlled by klippy directly even it is connected on the stm32 board.

we can not use the standard i2c driver code from the klipper now, because the bed distance has different i2c protocol and control logic, we need to write new code into the klipper with python and c code.

**Comment by ptegler** [comment]
> if we want to use it as settable trigger like proximity sensor, we need to add a new wires that connect to the sensor chip not data bus wires i2c to the mcu chip and also need a adjustable resistor like normal inductive proximity sensor, and there are so many that inductive sensor in the market.
> 
> The klipper has two parts software one is klippy written with python which runs on raspberrypi and another one is klipper written with C code which runs on MCU like stm32, so I think all the sensors are controlled by klippy directly even it is connected on the stm32 board.
> 
> we can not use the standard i2c driver code from the klipper now, because the bed distance has different i2c protocol and control logic, we need to write new code into the klipper with python and c code.

why 'trigger point' comment, is software not hardware.... a go-nogo trip point in configuration variables
